export const BUY_MOVIE = 'buyMovie'
export const RESET_HOME = 'resetHome'
export const FETCH_CASTS = 'fetchCasts'
export const FETCH_MOVIE = 'fetchMovie'
export const FETCH_REVIEWS = 'fetchReviews'
export const FETCH_NOW_PLAYING = 'fetchNowPlaying'
export const FETCH_SIMILAR_MOVIES = 'fetchSimilarMovies'
export const FETCH_RECOMMENDATIONS = 'fetchRecommendations'
