export const FETCH_CASTS = 'fetchCasts'
export const FETCH_MOVIE = 'fetchMovie'
export const FETCH_NOW_PLAYING = 'fetchNowPlaying'
export const FETCH_SIMILAR_MOVIES = 'fetchSimilarMovies'
export const FETCH_RECOMMENDATIONS = 'fetchRecommendations'
